### ISSUE TITLE
AttributeError: 'int' object has no attribute '_root'

### ISSUE THREAD

**Issue by mrkheaven** [fishyboteso/fishyboteso#100]
After using the last line to install I get this error
AttributeError: 'int' object has no attribute '_root'

This is the full readout
PS C:\Users\Kristof> python -m fishy
C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\runpy.py:126: RuntimeWarning: 'fishy.__main__' found in sys.modules after import of package 'fishy', but prior to execution of 'fishy.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
created backup
launching please wait...
Traceback (most recent call last):
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\site-packages\fishy\__main__.py", line 105, in <module>
    main()
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\site-packages\fishy\__main__.py", line 84, in main
    if not gui.check_eula():
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\site-packages\fishy\gui\terms_gui.py", line 16, in check_eula
    _run_terms_window()
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\site-packages\fishy\gui\terms_gui.py", line 43, in _run_terms_window
    check_value = tk.IntVar(0)
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 564, in __init__
    Variable.__init__(self, master, value, name)
  File "C:\Users\Kristof\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'int' object has no attribute '_root'
PS C:\Users\Kristof>

What should I do ?
Thank you so much

**Comment by SemjonKerner** [comment]
Please use the intended python version 3.7.3 and check out the wiki for additional help first.

**Comment by mrkheaven** [comment]
https://www.python.org/downloads/release/python-373/ 
This link gives me the latest version not 3.7.3 where do I get the correct one please?

**Comment by adsau59** [comment]
@mrkheaven refer the installation guide https://github.com/fishyboteso/fishyboteso/wiki/Installation
