### ISSUE TITLE
Cant start fishy

### ISSUE THREAD

**Issue by VasekTryba4eB** [fishyboteso/fishyboteso#117]
PS C:\Users\xxx> python -m fishy
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\__main__.py", line 10, in <module>
    from fishy.gui import GUI, splash, update_dialog, check_eula
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\gui\__init__.py", line 1, in <module>
    from .gui import GUI
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\gui\gui.py", line 8, in <module>
    from ttkthemes import ThemedTk
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\ttkthemes\__init__.py", line 6, in <module>
    from ttkthemes.themed_tk import ThemedTk
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\ttkthemes\themed_tk.py", line 8, in <module>
    from ._widget import ThemedWidget
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\ttkthemes\_widget.py", line 10, in <module>
    from PIL import Image, ImageEnhance
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\PIL\__init__.py)

**Comment by adsau59** [comment]
can u please send the result of this command
`pip freeze`

**Comment by SemjonWilke** [comment]
no response
