### ISSUE TITLE
Linux Options?

### ISSUE THREAD

**Issue by jacobchins** [fishyboteso/fishyboteso#149]
I'm not sure where to post this, but the install package is specific for Windows obviously. Is there any chance of getting this to run through Linux, even if through wine? Thank you!

**Comment by adsau59** [comment]
porting should be pretty simple, all we do with win32api is 
1) check if the the game is in focus in [helper.py](https://github.com/fishyboteso/fishyboteso/blob/b6e543a9e3bdc0671d954d5920479ba8ad2e7e6f/fishy/helper/helper.py#L235)
2) get location of the game window in [window_server.py](https://github.com/fishyboteso/fishyboteso/blob/b6e543a9e3bdc0671d954d5920479ba8ad2e7e6f/fishy/engine/common/window_server.py#L69-L70)

if these calls are abstracted, and equivalent calls are done for linux, theres no reason fishy wouldn't work for it, as everything else fishy does isn't platform dependent

**Comment by adsau59** [comment]
Only issue is, none of the devs daily drives linux, so its going to be a big task to setup linux and dev environment to test this out

if you already play the game on linux, I'd recommend u try setting up the fishy dev environment and giving it a go for making it compatible with linux... let me know if you are interested, i could do the abstraction for u so that u can simply extend the interface and implement linux dependent calls and try it out

**Comment by adsau59** [comment]
@jacobchins please let me know if you are interested

**Comment by jacobchins** [comment]
@adsau59 I would be happy to help however I can. I'm new-ish to Linux and don't know what setting up the dev environment would look like. I am currently playing on the Steam Deck when not on Windows. Let me know if I can help in any way or if there's a better way to communicate!

**Comment by adsau59** [comment]
@jacobchins we can chat on [discord](http://discord.definex.in)

steam deck would be fine, although i would recommend you to use monitor/kb/mouse for development 😉

you can follow the [how to develop?](https://github.com/fishyboteso/fishyboteso/wiki/How-to-Develop%3F) guide to setup your dev environment... you just have to clone the project, install python and an ide

while you setup the project, i'll abstract the win32api

**Comment by adsau59** [comment]
@jacobchins u just have to fill in the [linux.py](https://github.com/fishyboteso/fishyboteso/blob/c5d1cb67cf7131d0678e2fa00a9025653b62ee4d/fishy/osservices/linux.py) script as described by its interface, once that is done... fishy should be able to work with linux

**Comment by jacobchins** [comment]
I messaged an admin on the discord and am waiting to hear back!

**Comment by adsau59** [comment]
> I messaged an admin on the discord and am waiting to hear back!

yeah, we can chat on #dev channel on the server, so that if anyone else is interested, they can join in the thread

**Comment by BDadmehr0** [comment]
Hello, I am more interested in this topic and I want to develop the program on Linux

**Comment by adsau59** [comment]
> Hello, I am more interested in this topic and I want to develop the program on Linux

Hi, all u need to do is fill in the [linux.py](https://github.com/fishyboteso/fishyboteso/blob/dd404741fef9de2c8cf1b6d6941680154b4f3b3f/fishy/osservices/linux.py#L7-L29) file, and then uncomment [this](https://github.com/fishyboteso/fishyboteso/blob/dd404741fef9de2c8cf1b6d6941680154b4f3b3f/fishy/osservices/os_services.py#L75-L79)

**Comment by BDadmehr0** [comment]
> > Hello, I am more interested in this topic and I want to develop the program on Linux
> 
> Hi @BDadmehr0 , all u need to do is fill in the [linux.py](https://github.com/fishyboteso/fishyboteso/blob/dd404741fef9de2c8cf1b6d6941680154b4f3b3f/fishy/osservices/linux.py#L7-L29) file, and then uncomment [this](https://github.com/fishyboteso/fishyboteso/blob/dd404741fef9de2c8cf1b6d6941680154b4f3b3f/fishy/osservices/os_services.py#L75-L79)
> 
> Description for what each of the functions need to do, you can find [here](https://github.com/fishyboteso/fishyboteso/blob/dd404741fef9de2c8cf1b6d6941680154b4f3b3f/fishy/osservices/os_services.py#L15-L60)... you can even take a look at the windows implementation to get an idea what is being done exactly
> 
> let me know if you need more info.

Yes, I read the source code and I am filling the functions, but I encountered a strange problem .config :
ImportError: cannot import name 'os_services' from partially initialized module 'fishy.osservices.os_services' (most likely due to a circular import) (/home/dadmehremami/.local/lib/python3.11/site-packages/fishy/osservices/os_services.py)

**Comment by BDadmehr0** [comment]
> > 
> 
> can u link ur fork pls, will have to check out the code to see what the issue is

https://github.com/BDadmehr0/fishyboteso

**Comment by adsau59** [comment]
can u send the  entire call stack for the error too, im not sure how its giving error... i have imported the same way for windows, and it works fine

**Comment by BDadmehr0** [comment]
> can u send the entire call stack for the error too, im not sure how its giving error... i have imported the same way for windows, and it works fine

I run the linux.py code for testing, it gives the following error:

Traceback (most recent call last):
  File "/home/dadmehremami/Documents/GitHub/fishyboteso/fishy/osservices/linux.py", line 6, in <module>
    from fishy.osservices.os_services import IOSServices
  File "/home/dadmehremami/.local/lib/python3.11/site-packages/fishy/osservices/os_services.py", line 9, in <module>
    from fishy.helper.depless import singleton_proxy
  File "/home/dadmehremami/.local/lib/python3.11/site-packages/fishy/helper/__init__.py", line 1, in <module>
    from .config import Config
  File "/home/dadmehremami/.local/lib/python3.11/site-packages/fishy/helper/config.py", line 13, in <module>
    from fishy.osservices.os_services import os_services
ImportError: cannot import name 'os_services' from partially initialized module 'fishy.osservices.os_services' (most likely due to a circular import) (/home/dadmehremami/.local/lib/python3.11/site-packages/fishy/osservices/os_services.py)

**Comment by adsau59** [comment]
oh dont run linux.py directly, u'll need to run fishy from main for it to work... if you want directly run it for testing maybe dont import os_services, or import it under some some if condition

**Comment by BDadmehr0** [comment]
> oh dont run linux.py directly, u'll need to run fishy from main for it to work... if you want directly run it for testing maybe dont import os_services, or import it under some some if condition

Sorry, I wasn't paying attention at all

**Comment by BDadmehr0** [comment]
I don't understand this issue. I am adapting the service I cloned to Linux and when I run __main__.py it needs to be changed to the fishy library and it does not support Linux.

**Comment by adsau59** [comment]
I'm not sure what u mean, we can connect on discord, if you want to discuss the issue

**Comment by BDadmehr0** [comment]
> I'm not sure what u mean, we can connect on discord, if you want to discuss the issue

The problem is that my English is not good

**Comment by adsau59** [comment]
> it needs to be changed to the fishy library and it does not support Linux

are you getting errors? if you send logs/screenshots it'll help me understand the issue

before fishy code was dependent on win32api so i moved all the dep into a single python file which is only imported if the system is windows, ideally filling the linux.py should make it work for linux, but it is possible that some code outside fo windows.py in fishy would be coupled with the windows system, if you do find this kindof code let me know

**Comment by BDadmehr0** [comment]
> 

I feel that the fishy module that is used in most places is an exact copy of this project and I have to apply the changes in both.

**Comment by BDadmehr0** [comment]
I'm starting to fear something, after trying so hard to run the graphic window

@adsau59 

![20230807_071046.jpg](https://github.com/fishyboteso/fishyboteso/assets/134191240/b1d5a836-70c5-4493-8a17-6248d4d4b675)

**Comment by adsau59** [comment]
> I'm starting to fear something, after trying so hard to run the graphic window

not sure what u mean

**Comment by BDadmehr0** [comment]
Hello, I have a problem with saving the config files and program shortcuts.
We all know that the program must be run with root access, and this causes that every file that is saved on the desktop or in documents is saved in the root directory.
It means that the normal user can see the directories of the normal user's desktop, in order to be able to build the shortcut that has been created, he must go to the root directories.

[image](https://raw.githubusercontent.com/BDadmehr0/fishyboteso/main/Screenshot_2023-08-08_21-51-21.png)
