### ISSUE TITLE
Full Auto Calibration while game is in fullscreen doesn't work

### ISSUE THREAD

**Issue by Ronso20** [fishyboteso/fishyboteso#85]
Calibration while game is in fullscreen doesn't work. 

- i was able to calibrate it in fullscreen when i press F9 in game after i press calibration button in fishy, but it's not working everytime

**Comment by Ronso20** [comment]
Console log:

_Traceback (most recent call last):
  File "C:\Users\Ronso\AppData\Roaming\Python\Python39\site-packages\fishy\engine\fullautofisher\engine.py", line 86, in run
    log_raise("Game window not found")
  File "C:\Users\Ronso\AppData\Roaming\Python\Python39\site-packages\fishy\helper\helper.py", line 229, in log_raise
    raise Exception(msg)
Exception: Game window not found_

**Comment by adsau59** [comment]
was fixed in previous version of fishy, please reopen the issue if u face it again
