### ISSUE TITLE
Windows api call which returns the documents directory is getting exception

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#94]
happens when used with vpn

```
C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\runpy.py:125: RuntimeWarning: 'fishy.__main__' found in sys.modules after import of package 'fishy', but prior to execution of 'fishy.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\__main__.py", line 105, in <module>
    main()
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\__main__.py", line 73, in main
    config.init()
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\helper\config.py", line 94, in init
    config._instance.initialize()
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\helper\config.py", line 43, in initialize
    if os.path.exists(filename()):
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\helper\config.py", line 20, in filename
    return os.path.join(get_documents(), name)
  File "C:\Users\b703356\AppData\Local\Programs\Python\Python37\lib\site-packages\fishy\helper\helper.py", line 220, in get_documents
    return shell.SHGetFolderPath(0, shellcon.CSIDL_PERSONAL, None, 0)
pywintypes.com_error: (-2147024843, 'The network path was not found.', None, None)
```

**Comment by adsau59** [comment]
related to #121 ?
