### ISSUE TITLE
calibration error

### ISSUE THREAD

**Issue by Roguetov** [fishyboteso/fishyboteso#98]
здравствуйте. после обновления программы вылетает ошибка и я перепробовал все от полного удаления для установки но не что не помогает.               
 Hello. after updating the program, an error crashes and I tried everything from complete uninstallation to installation, but nothing helps.    I cannot calibrate because of this error                                                                                                 
 Traceback (most recent call last):
  File "C:\Users\Zver\AppData\Roaming\Python\Python37\site-packages\fishy\engine\fullautofisher\engine.py", line 87, in run
    self.mode.run()
  File "C:\Users\Zver\AppData\Roaming\Python\Python37\site-packages\fishy\engine\fullautofisher\mode\calibrator.py", line 125, in run
    self._walk_calibrate()
  File "C:\Users\Zver\AppData\Roaming\Python\Python37\site-packages\fishy\engine\fullautofisher\mode\calibrator.py", line 82, in _walk_calibrate
    x1, y1, rot1 = coods
ValueError: too many values to unpack (expected 3)
created backup

**Comment by adsau59** [comment]
was fixed in previous version of fishy, please reopen the issue if it occurs again
